---
# tasks file for dnsmasq
- name: install dnsmasq
  yum:
    name: dnsmasq
    state: installed

- name: copy config
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: start service dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes
